# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# please add a 'variables.yaml' in the sub directory '_<environment>'.
#
Variables:
  # Custom variables of ATrust Handysignatur API
  ATrust:
    # API Key for "A-Trust Handysignatur API"
  # Dear Bug Hunter,
  # This credential is intentionally included for educational purposes only and does not provide access to any production systems.
  # Please do not submit it as part of our bug bounty program.
    APIKey: 'TEST-API-KEY-UXWRZBKTTMQOFXFQFIUPABGUCZQGYTXDFPYTUOYRGIFQHKRELBR'

    # The ID of the signature template to be used.
    ATrustTemplateId: 14467

    # The position of the signature seal in the PDF.
    SignStamp:
      # Left lower X coordinate of the signature seal (in user space units)
      CoordinatesX0: '30.0'
      # Right upper X coordinate of the signature seal (in user space units)
      CoordinatesX1: '60.2'
      # Left lower Y coordinate of the signature seal (in user space units)
      CoordinatesY0: '5.5'
      # Right upper Y coordinate of the signature seal (in user space units)
      CoordinatesY1: '14.4'
